# NumPy：從陣列到高效數值運算


## 認識 NumPy：一週餐費一起算

下班買便當、早餐店加蛋、下午買飲料，一筆金額不難算；如果要把整週、整班或整家店的數字一起調整，反覆寫加減乘除就容易漏掉。NumPy 適合讓「同一條計算規則」作用在一整批數值上。

`import numpy as np` 是載入套件並取簡稱；`np` 是慣例，不是 Python 關鍵字。`np.array(...)` 把現有數值建立成陣列。`餐費 * 2` 的意思要看餐費是哪一種物件：List 重複內容，數值陣列則讓每個數字乘二。這叫「逐元素運算」，元素就是其中一格的值。

| 工具      | 適合情境                         | 需要留意                           |
| --------- | -------------------------------- | ---------------------------------- |
| List      | 購物項目、少量混合資料           | 乘法可能是重複，不是金額翻倍       |
| ndarray   | 同一批價格、成績、數量做相同運算 | 主要依位置配對，自己維護位置的意義 |
| DataFrame | 有姓名、日期、類別的表格         | 運算可能按標籤對齊                 |


In [1]:
"""認識 NumPy：一週餐費一起算。對應 numpy.md 第 01 節。"""

import numpy as np
import pandas as pd

# 五天午餐費；List 的乘二會重複整份清單。
lunch_list = [90, 110, 100, 120, 80]
print("List 乘二：", lunch_list * 2)

# ndarray 的乘二是逐格計算金額。
lunch = np.array(lunch_list)
print("陣列乘二：", lunch * 2)
print("每天少花十元：", lunch - 10)
print("整週午餐費：", lunch.sum())

# 同一批數字也可以加上星期標籤，交給 Pandas 呈現。
report = pd.DataFrame({
    "星期": ["一", "二", "三", "四", "五"], 
    "餐費": lunch
    })
print(report)

List 乘二： [90, 110, 100, 120, 80, 90, 110, 100, 120, 80]
陣列乘二： [180 220 200 240 160]
每天少花十元： [ 80 100  90 110  70]
整週午餐費： 500
  星期   餐費
0  一   90
1  二  110
2  三  100
3  四  120
4  五   80


NumPy 常能把大量數值運算交給底層實作，減少 Python 逐次執行迴圈的負擔。但小資料、轉換成本、複雜文字處理都可能讓它沒有速度優勢；先追求計算正確與可讀性，不要把「用了 NumPy」當作一定比較快。

## ndarray：一維、二維與多維陣列

「維度」可以先理解成：要用幾個位置，才能找到一個數字。一維是排成一列的記錄；二維要指定第幾列與第幾欄；三維再增加第幾張表。

以飲料銷量為例，一天三種飲料是 `(3,)`；兩天、每天三種飲料是 `(2, 3)`；兩間店、每間兩天、每天三種飲料是 `(2, 2, 3)`。三維不需要想成抽象立體空間，只要想成兩份相同格式的表格。

我們固定把「列」當橫向一排（row），把「欄」當直向一欄（column）。

In [2]:
"""ndarray：一維、二維與多維陣列。對應 numpy.md 第 02 節。"""

import numpy as np

# 一維：紅茶、奶茶、綠茶，順序固定。
one_day = np.array([20, 15, 10])

# 二維：列是日期，欄是飲料。
one_shop = np.array([[20, 15, 10], [30, 10, 20]])

# 三維：店別、日期、飲料。
two_shops = np.array([one_shop, [[10, 5, 8], [15, 8, 12]]])

print("一天：", one_day.shape)
print("一店兩天：", one_shop.shape)
print("兩店：", two_shops.shape)
# 索引從 0 開始：第二間、第一天、第三種飲料。
print("指定銷量：", two_shops[1, 0, 2])


一天： (3,)
一店兩天： (2, 3)
兩店： (2, 2, 3)
指定銷量： 8


## 建立陣列：從空白紀錄到固定間隔

### zeros()：準備指定大小的空白資料表

- (2, 3) 表示 2 列、3 欄。
- 零只是初始值，不會自動代表缺失資料。
- 正確寫法是 zeros((2, 3))，不能寫成 zeros(2, 3)。
- 每個位置先放入 1：使用 ones

In [3]:
sales_table = np.zeros((2, 3), dtype=int)
print(sales_table)

[[0 0 0]
 [0 0 0]]


### arange()：按照固定「間隔」建立陣列

- 格式：arange(起點, 終點, 間隔)
- 按照固定「數量」建立陣列：使用 linspace

In [ ]:
numbers = np.arange(0, 10, 2)
print(numbers)



[0 2 4 6 8]
[  0.  25.  50.  75. 100.]


### linspace()：按照固定「數量」建立陣列

In [5]:
points = np.linspace(0, 100, 5)
print(points)

[  0.  25.  50.  75. 100.]


## 查看陣列：先認識資料再運算

In [6]:
# 先確認每一列、每一欄與單位代表什麼
import numpy as np

electricity = np.array([
    [8, 10, 9],   # 家庭 A
    [6, 7, 8]     # 家庭 B
])

print(electricity)

[[ 8 10  9]
 [ 6  7  8]]


### shape：查看每一軸的長度

In [7]:
print(electricity.shape)

(2, 3)


### size：查看元素總數

In [8]:
print(electricity.size)

6


### ndim：總共有幾個維度

In [11]:
import numpy as np

a = np.array([10, 20, 30])

print(a.shape) # (3,)：有一個維度，該維度包含 3 個元素
print(a.ndim) # 1：這是一維陣列

(3,)
1


### dtype：查看資料型態

In [9]:
print(electricity.dtype)

int64


## 資料型態與轉換：數字外觀不等於數字

In [ ]:
"""看起來像數字，不代表資料型態是數字"""
import numpy as np

prices = np.array(["120", "85", "99.5"])

print(prices) # ['120' '85' '99.5']
print(prices.dtype) # <U4，表示文字型態

['120' '85' '99.5']
<U4


In [14]:
"""文字無法直接當成數字運算"""
prices = np.array(["120", "85", "99.5"])
# prices + 10 # 會發生錯誤

必須先將文字轉換成數值型態

- 使用 astype(float) 轉換成小數
- astype() 預設會建立轉換後的陣列

In [15]:
prices = np.array(["120", "85", "99.5"])
numeric_prices = prices.astype(float)

print(numeric_prices) # [120.   85.   99.5]
print(numeric_prices.dtype) # float64

[120.   85.   99.5]
float64


In [16]:
import numpy as np

# 字串中的純數字可轉為浮點數；「待確認」則不能直接 astype。
price_text = np.array(["120", "85.5", "99.9"])
prices = price_text.astype(float)
print("九折：", prices * 0.9)
print("截去小數：", np.array([3.8, -3.8]).astype(int))
# 先轉浮點數，才能保留修改後的小數。
editable = np.array([100, 200]).astype(float)
editable[0] = 89.5
print("修改後：", editable)
print("浮點比較：", np.isclose(0.1 + 0.2, 0.3))
print("取最近偶數：", np.round([2.5, 3.5]))

九折： [108.    76.95  89.91]
截去小數： [ 3 -3]
修改後： [ 89.5 200. ]
浮點比較： True
取最近偶數： [2. 4.]


## 索引與切片：取出想看的時間區間

In [ ]:
import numpy as np

temperatures = np.array([22, 24, 26, 25, 23])
# 索引用來取出單一元素
print(temperatures[0])

# 切片用來取出一段資料
selected = temperatures[0:3] # 陣列[開始:停止:步長]
print(selected)

22
[22 24 26]


## 布林遮罩

布林遮罩(Boolean Mask)可以把它想成一張「篩選表」。

### 建立布林遮罩

如果想知道「哪些商品價格超過 100 元」，可以直接寫：

In [1]:
import numpy as np

### 建立商品價格
prices = np.array([50, 120, 80, 200, 150])

### 判斷每個價格是否大於 100
mask = prices > 100

print(mask)

[False  True False  True  True]


### 使用遮罩篩選資料

In [2]:
import numpy as np


### 建立商品價格
prices = np.array([50, 120, 80, 200, 150])
mask = prices > 100 ### 建立布林遮罩

### 使用遮罩篩選
result = prices[mask]
print(result)

[120 200 150]


### 多個條件同時篩選

| 運算子  | 意思 | 範例                                 |
| ---- | -- | ---------------------------------- |
| `&`  | 而且 | `(prices >= 80) & (prices <= 150)` |
| `\|` | 或者 | `(prices < 80) \| (prices > 150)`  |
| `~`  | 反向 | `~(prices > 100)`                  |

例如現在想找「價格介於 80 元到 150 元之間的商品」，就寫`(prices >= 100) & (prices <= 180)`。

注意，不是`(prices >= 80) and (prices <= 150)`，因為 Python 的 and、or 處理的是「整體 True / False」。NumPy 需要的是逐元素判斷


In [4]:
import numpy as np

### 建立商品價格
prices = np.array([50, 120, 80, 200, 150])

### 價格大於等於 80，而且小於等於 150
mask = (prices >= 80) & (prices <= 150)

print(prices[mask])

[120  80 150]


### mask.sum()：有幾筆符合條件
布林值在加總時：
```
True  → 1
False → 0
```
因此可以直接計算符合條件的商品數量

In [5]:
import numpy as np

### 建立商品價格
prices = np.array([50, 120, 80, 200, 150])

### 找出價格超過 100 的商品
mask = prices > 100

print(mask)

### 計算符合條件的數量
count = mask.sum()
print("超過 100 元的商品數量：", count)

[False  True False  True  True]
超過 100 元的商品數量： 3


### any()：有沒有任何一筆符合

如果只想知道「有沒有商品超過 180 元？」

In [6]:
import numpy as np


### 建立商品價格
prices = np.array([50, 120, 80, 200, 150])


### 判斷是否至少有一個商品超過 180 元
mask = prices > 180

print(mask)
print(mask.any())

[False False False  True False]
True


### all()：是不是全部都符合
如果只想知道「所有商品是不是都至少 50 元？」

In [ ]:
import numpy as np


### 建立商品價格
prices = np.array([50, 120, 80, 200, 150])


### 判斷所有商品是否都大於等於 50
mask = prices >= 50

print(mask)
print(mask.all())

### 商品名稱與價格一起篩選
布林遮罩真正好用的地方，是可以同步篩選不同陣列。

In [ ]:
import numpy as np


### 建立商品資料
products = np.array([
    "紅茶",
    "珍珠奶茶",
    "雞排",
    "牛肉麵",
    "咖啡"
])

prices = np.array([
    30,
    70,
    90,
    180,
    120
])


### 找出價格大於等於 100 的商品
mask = prices >= 100


### 使用相同遮罩篩選商品名稱與價格
selected_products = products[mask]
selected_prices = prices[mask]

print(selected_products)
print(selected_prices)

### 直接使用遮罩修改原始資料

遮罩不只能「找資料」，還可以直接修改資料。

例如「200 元以上的商品全部打九折」



In [7]:
import numpy as np


### 建立商品價格
prices = np.array([80, 120, 200, 250, 300], dtype=float)


### 找出 200 元以上的商品
mask = prices >= 200


### 將符合條件的商品打九折
prices[mask] = prices[mask] * 0.9

print(prices)

[ 80. 120. 180. 225. 270.]


## 修改陣列：view 與 copy

### 最基本的情況：b = a

可以想成：
```
a ──┐
    ├──→ [100, 120, 150, 180] -> 它們都指向同一個 NumPy 陣列物件
b ──┘
```

### 用 is 檢查是不是同一個物件

Python 可以用 is 判斷兩個變數是不是指向同一個物件：

In [8]:
import numpy as np

a = np.array([100, 120, 150, 180])
b = a

### 判斷是否為同一個物件
print(a is b)

True


### 切片比較特別：會產生 view


In [ ]:
import numpy as np


### 建立原始價格
a = np.array([100, 120, 150, 180])


### 取出前兩筆資料
b = a[:2]

print("a：", a)
print("b：", b)
print(a is b) # False

# 看起來 a、b 已經不是同一個物件。這時候的b是 view(檢視)。


a： [100 120 150 180]
b： [100 120]
False


### View 是什麼

```
原始資料 a
┌───────────────────────┐
│ 100 │ 120 │ 150 │ 180 │
└───────────────────────┘
```

```
b = a[:2]

原始資料 a
┌───────────────────────┐
│ 100 │ 120 │ 150 │ 180 │
└─▲─────▲───────────────┘
  │     │
  └── b ┘
```
所以 b 雖然是一個新的陣列物件，底下的資料仍然來自 a。

In [11]:
# 修改 view，原始資料也會改
import numpy as np


### 建立原始價格
a = np.array([100, 120, 150, 180])

b = a[:2] ### 取得前兩筆資料的 view
b[0] = 50 ### 修改 b

print("a：", a)
print("b：", b)

a： [ 50 120 150 180]
b： [ 50 120]


### copy()：真正複製一份資料

如果你的目的就是「拿資料出來試算，但不要動到原始資料」，就使用`.copy()`

In [12]:
import numpy as np

a = np.array([100, 120, 150, 180]) ### 建立原始價格
b = a[:2].copy() ### 複製前兩筆資料
b[0] = 50 ### 修改複製後的資料

print("a：", a)
print("b：", b)

a： [100 120 150 180]
b： [ 50 120]


## 調整形狀：重新排版，不是重新排序

In [ ]:
# 假設記錄了連續 14 天的餐費：
import numpy as np


### 建立 14 天餐費
expenses = np.array([
    120, 150, 100, 180, 130, 200, 160,
    140, 170, 110, 190, 150, 220, 180
])

print(expenses)
print("形狀：", expenses.shape) # 目前是一維陣列，總共有 14 個元素。

[120 150 100 180 130 200 160 140 170 110 190 150 220 180]
形狀： (14,)


### reshape()：改變陣列形狀


In [14]:
import numpy as np


### 建立 14 天餐費
expenses = np.array([
    120, 150, 100, 180, 130, 200, 160,
    140, 170, 110, 190, 150, 220, 180
])

### 重新排列成 2 週，每週 7 天
weekly = expenses.reshape(2, 7)

print(weekly)
print("形狀：", weekly.shape)

[[120 150 100 180 130 200 160]
 [140 170 110 190 150 220 180]]
形狀： (2, 7)


### -1：讓 NumPy 自己算

有時候我們只知道「我要分成兩週，但懶得算每週有幾格。」


In [15]:
import numpy as np


### 建立 14 天餐費
expenses = np.array([
    120, 150, 100, 180, 130, 200, 160,
    140, 170, 110, 190, 150, 220, 180
])


### 指定 2 列，欄數讓 NumPy 自動計算
weekly = expenses.reshape(2, -1)

print(weekly)
print("形狀：", weekly.shape)

[[120 150 100 180 130 200 160]
 [140 170 110 190 150 220 180]]
形狀： (2, 7)


### ravel()：攤平成一維


In [16]:
weekly = np.array([
    [120, 150, 100, 180, 130, 200, 160],
    [140, 170, 110, 190, 150, 220, 180]
])

# 現在想重新攤平成一條，可以使用：
result = weekly.ravel()
print(result)
print(result.shape)

[120 150 100 180 130 200 160 140 170 110 190 150 220 180]
(14,)


## .T：交換列與欄

In [ ]:
weekly = np.array([
    [120, 150, 100, 180, 130, 200, 160],
    [140, 170, 110, 190, 150, 220, 180]
])

print(weekly.shape)

result = weekly.T
# result = weekly.transpose() 跟上一行是依樣意思

print(result)
print(result.shape)

(2, 7)
[[120 140]
 [150 170]
 [100 110]
 [180 190]
 [130 150]
 [200 220]
 [160 180]]
(7, 2)


### 想把一維變成直欄，不能用.T，要用reshape(-1, 1)

In [19]:
import numpy as np


### 建立一維陣列
a = np.array([100, 120, 150])


### 轉成直欄
column = a.reshape(-1, 1)

print(column)
print("形狀：", column.shape)

[[100]
 [120]
 [150]]
形狀： (3, 1)


## 陣列合併與拆分

「你是要把資料「接長」，還是要多增加一個「分類層級」？」，這就是 concatenate() 和 stack() 最大的差別。

In [20]:
import numpy as np


### 建立早班銷售資料
morning = np.array([
    [10, 20, 15],
    [12, 18, 22]
])

print(morning)
print("形狀：", morning.shape)

[[10 20 15]
 [12 18 22]]
形狀： (2, 3)


### concatenate()：沿著原本的方向接起來


In [21]:
import numpy as np


### 前兩天
first = np.array([
    [10, 20, 15],
    [12, 18, 22]
])


### 後兩天
second = np.array([
    [14, 25, 17],
    [16, 21, 20]
])

result = np.concatenate(
    [first, second],
    axis=0 # 依「列(row)」方向增加資料
    # axis=1 # 依「欄(column)」方向增加資料
)

print(result)
print("形狀：", result.shape)

[[10 20 15]
 [12 18 22]
 [14 25 17]
 [16 21 20]]
形狀： (4, 3)


### stack()：不是接長，而是新增一個軸

In [23]:
# 早班
morning = np.array([ # 2 天 × 3 種商品
    [10, 20, 15],
    [12, 18, 22]
])

# 中班
evening = np.array([ # 2 天 × 3 種商品
    [15, 25, 20],
    [18, 22, 30]
])

In [ ]:
# 如果直接用concatenate()合併成(4, 3)資料，班別這個結構消失了。
sales = np.concatenate(
    [morning, evening],
    axis=0
)

print(sales)
print("\n形狀：")
print(sales.shape)

[[10 20 15]
 [12 18 22]
 [15 25 20]
 [18 22 30]]

形狀：
(4, 3)


In [27]:
# 用 stack() 保留「班別」這個層級
### 新增班別這個軸
sales = np.stack(
    [morning, evening],
    axis=0
)

print(sales)

print("\n形狀：")
print(sales.shape)

[[[10 20 15]
  [12 18 22]]

 [[15 25 20]
  [18 22 30]]]

形狀：
(2, 2, 3)


```
(2, 2, 3)
 ↑  ↑  ↑
班別 日期 商品
```

## 向量化：把共同規則寫一次

假設團購三種餐點：

In [28]:
import numpy as np

prices = np.array([90, 110, 80]) ### 商品單價
quantities = np.array([2, 1, 3]) ### 購買數量

現在要算每項商品的小計

In [30]:
# 傳統寫法可以用迴圈
total = 0
for price, quantity in zip(prices, quantities):
    total += price * quantity
print(total)

530


In [31]:
### NumPy 可以直接逐元素計算商品小計
subtotals = prices * quantities

print(subtotals)

[180 110 240]


## Broadcasting：廣播機制：不同形狀如何配對
假設三戶家庭分別購買牛奶與雞蛋：

In [ ]:
import numpy as np

### 三戶家庭的購買數量
quantities = np.array([
    [2, 1],
    [1, 3],
    [4, 2]
])

### 牛奶與雞蛋單價
prices = np.array([80, 60]) # 這是一微陣列，如果要以二維振烈去看，就是(1, 2)

print("數量形狀：", quantities.shape)
print("價格形狀：", prices.shape)

數量形狀： (3, 2)
價格形狀： (2,)


In [33]:
### 計算每戶各商品小計
subtotals = quantities * prices
print(subtotals)

[[160  60]
 [ 80 180]
 [320 120]]


Broadcasting會從從 shape 的右邊開始比較。
```
(3, 2)
(1, 2)
右邊都是2，所以可以計算
```

只要滿足以下兩個條件即可：
- 兩邊數字相同 → 可以
- 其中一邊是 1 → 可以

如果想要再增加折扣

In [35]:
discounts = np.array([
    0.9,
    1.0,
    0.8
])

print(discounts.shape) # (3,)
# print(subtotals * discounts) # (3,2) 與 (1, 3)無法Broadcasting

(3,)


In [38]:
### 處理方式，把把折扣變成 (3, 1)
discounts = np.array([
    0.9,
    1.0,
    0.8
])

discounts = discounts.reshape(3, -1)
print(discounts.shape)
print(subtotals * discounts) 

(3, 1)
[[144.  54.]
 [ 80. 180.]
 [256.  96.]]


## 數學函式與條件運算

### np.where()：像 Excel 的 IF

In [39]:
# 假設三筆訂單：
### 訂單金額
orders = np.array([320, 500, 780])
### 根據訂單金額決定運費
shipping = np.where(orders >= 500, 0, 60)
print(shipping)

[60  0  0]


### np.clip()：限制上下限

In [40]:
# 假設會員點數
points = np.array([ -5, 30, 150])

# 規定：
# 最低 0
# 最高 100

### 將點數限制在 0～100
result = np.clip(
    points,
    0,
    100
)

print(result)

[  0  30 100]


### np.abs()：只看差多少

In [41]:
# 假設目標消費是 500：
orders = np.array([
    320,
    500,
    780
])

### 計算與 500 的距離
difference = np.abs(orders - 500)
print(difference)

[180   0 280]


### np.sqrt()：平方根

In [43]:
import numpy as np

### 計算平方根
values = np.array([ 4, 9, 16])
result = np.sqrt(values)
print(result)

[2. 3. 4.]


### floor()：往下取整

In [44]:
values = np.array([1.2, 1.8, 2.9])
### 往負無限方向取整
print(np.floor(values))

[1. 1. 2.]


### ceil()：往上取整

In [45]:
values = np.array([1.2, 1.8, 2.9])
### 往負無限方向取整
print(np.ceil(values))

[2. 2. 3.]


> 反正還有很多函數，就遇到需求，再用GPT查就好了~

![](./numpy_assets/我要請假.png)