# NumPy：從陣列到高效數值運算


## 認識 NumPy：一週餐費一起算

下班買便當、早餐店加蛋、下午買飲料，一筆金額不難算；如果要把整週、整班或整家店的數字一起調整，反覆寫加減乘除就容易漏掉。NumPy 適合讓「同一條計算規則」作用在一整批數值上。

`import numpy as np` 是載入套件並取簡稱；`np` 是慣例，不是 Python 關鍵字。`np.array(...)` 把現有數值建立成陣列。`餐費 * 2` 的意思要看餐費是哪一種物件：List 重複內容，數值陣列則讓每個數字乘二。這叫「逐元素運算」，元素就是其中一格的值。

| 工具      | 適合情境                         | 需要留意                           |
| --------- | -------------------------------- | ---------------------------------- |
| List      | 購物項目、少量混合資料           | 乘法可能是重複，不是金額翻倍       |
| ndarray   | 同一批價格、成績、數量做相同運算 | 主要依位置配對，自己維護位置的意義 |
| DataFrame | 有姓名、日期、類別的表格         | 運算可能按標籤對齊                 |


In [1]:
"""認識 NumPy：一週餐費一起算。對應 numpy.md 第 01 節。"""

import numpy as np
import pandas as pd

# 五天午餐費；List 的乘二會重複整份清單。
lunch_list = [90, 110, 100, 120, 80]
print("List 乘二：", lunch_list * 2)

# ndarray 的乘二是逐格計算金額。
lunch = np.array(lunch_list)
print("陣列乘二：", lunch * 2)
print("每天少花十元：", lunch - 10)
print("整週午餐費：", lunch.sum())

# 同一批數字也可以加上星期標籤，交給 Pandas 呈現。
report = pd.DataFrame({
    "星期": ["一", "二", "三", "四", "五"], 
    "餐費": lunch
    })
print(report)

List 乘二： [90, 110, 100, 120, 80, 90, 110, 100, 120, 80]
陣列乘二： [180 220 200 240 160]
每天少花十元： [ 80 100  90 110  70]
整週午餐費： 500
  星期   餐費
0  一   90
1  二  110
2  三  100
3  四  120
4  五   80


NumPy 常能把大量數值運算交給底層實作，減少 Python 逐次執行迴圈的負擔。但小資料、轉換成本、複雜文字處理都可能讓它沒有速度優勢；先追求計算正確與可讀性，不要把「用了 NumPy」當作一定比較快。

## ndarray：一維、二維與多維陣列

「維度」可以先理解成：要用幾個位置，才能找到一個數字。一維是排成一列的記錄；二維要指定第幾列與第幾欄；三維再增加第幾張表。

以飲料銷量為例，一天三種飲料是 `(3,)`；兩天、每天三種飲料是 `(2, 3)`；兩間店、每間兩天、每天三種飲料是 `(2, 2, 3)`。三維不需要想成抽象立體空間，只要想成兩份相同格式的表格。

我們固定把「列」當橫向一排（row），把「欄」當直向一欄（column）。

In [2]:
"""ndarray：一維、二維與多維陣列。對應 numpy.md 第 02 節。"""

import numpy as np

# 一維：紅茶、奶茶、綠茶，順序固定。
one_day = np.array([20, 15, 10])

# 二維：列是日期，欄是飲料。
one_shop = np.array([[20, 15, 10], [30, 10, 20]])

# 三維：店別、日期、飲料。
two_shops = np.array([one_shop, [[10, 5, 8], [15, 8, 12]]])

print("一天：", one_day.shape)
print("一店兩天：", one_shop.shape)
print("兩店：", two_shops.shape)
# 索引從 0 開始：第二間、第一天、第三種飲料。
print("指定銷量：", two_shops[1, 0, 2])


一天： (3,)
一店兩天： (2, 3)
兩店： (2, 2, 3)
指定銷量： 8


## 建立陣列：從空白紀錄到固定間隔

### zeros()：準備指定大小的空白資料表

- (2, 3) 表示 2 列、3 欄。
- 零只是初始值，不會自動代表缺失資料。
- 正確寫法是 zeros((2, 3))，不能寫成 zeros(2, 3)。
- 每個位置先放入 1：使用 ones

In [3]:
sales_table = np.zeros((2, 3), dtype=int)
print(sales_table)

[[0 0 0]
 [0 0 0]]


### arange()：按照固定「間隔」建立陣列

- 格式：arange(起點, 終點, 間隔)
- 按照固定「數量」建立陣列：使用 linspace

In [ ]:
numbers = np.arange(0, 10, 2)
print(numbers)



[0 2 4 6 8]
[  0.  25.  50.  75. 100.]


### linspace()：按照固定「數量」建立陣列

In [5]:
points = np.linspace(0, 100, 5)
print(points)

[  0.  25.  50.  75. 100.]


## 查看陣列：先認識資料再運算

In [6]:
# 先確認每一列、每一欄與單位代表什麼
import numpy as np

electricity = np.array([
    [8, 10, 9],   # 家庭 A
    [6, 7, 8]     # 家庭 B
])

print(electricity)

[[ 8 10  9]
 [ 6  7  8]]


### shape：查看每一軸的長度

In [7]:
print(electricity.shape)

(2, 3)


### size：查看元素總數

In [8]:
print(electricity.size)

6


### ndim：總共有幾個維度

In [11]:
import numpy as np

a = np.array([10, 20, 30])

print(a.shape) # (3,)：有一個維度，該維度包含 3 個元素
print(a.ndim) # 1：這是一維陣列

(3,)
1


### dtype：查看資料型態

In [9]:
print(electricity.dtype)

int64


## 資料型態與轉換：數字外觀不等於數字

In [ ]:
"""看起來像數字，不代表資料型態是數字"""
import numpy as np

prices = np.array(["120", "85", "99.5"])

print(prices) # ['120' '85' '99.5']
print(prices.dtype) # <U4，表示文字型態

['120' '85' '99.5']
<U4


In [14]:
"""文字無法直接當成數字運算"""
prices = np.array(["120", "85", "99.5"])
# prices + 10 # 會發生錯誤

必須先將文字轉換成數值型態

- 使用 astype(float) 轉換成小數
- astype() 預設會建立轉換後的陣列

In [15]:
prices = np.array(["120", "85", "99.5"])
numeric_prices = prices.astype(float)

print(numeric_prices) # [120.   85.   99.5]
print(numeric_prices.dtype) # float64

[120.   85.   99.5]
float64


In [16]:
import numpy as np

# 字串中的純數字可轉為浮點數；「待確認」則不能直接 astype。
price_text = np.array(["120", "85.5", "99.9"])
prices = price_text.astype(float)
print("九折：", prices * 0.9)
print("截去小數：", np.array([3.8, -3.8]).astype(int))
# 先轉浮點數，才能保留修改後的小數。
editable = np.array([100, 200]).astype(float)
editable[0] = 89.5
print("修改後：", editable)
print("浮點比較：", np.isclose(0.1 + 0.2, 0.3))
print("取最近偶數：", np.round([2.5, 3.5]))

九折： [108.    76.95  89.91]
截去小數： [ 3 -3]
修改後： [ 89.5 200. ]
浮點比較： True
取最近偶數： [2. 4.]


## 索引與切片：取出想看的時間區間

In [ ]:
import numpy as np

temperatures = np.array([22, 24, 26, 25, 23])
# 索引用來取出單一元素
print(temperatures[0])

# 切片用來取出一段資料
selected = temperatures[0:3] # 陣列[開始:停止:步長]
print(selected)

22
[22 24 26]
